site_name: Lifehacker
site_url: https://ludwikc.github.io/Lifehacker
docs_dir: docs
theme:
  name: material
  palette:
    primary: black
    accent: blue
  features:
    - navigation.tabs
    - navigation.tabs.sticky

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
#  - pub-obsidian:
#      obsidian_dir: .obsidian
#  - pub-meta:
#      publish:
#        file_default: publish
#        file_warn_on_missing: true
#        dir_default: published

copyright: |
  &copy; 2024 <a href="https://siadlak.com"  target="_blank" rel="noopener">Ludwik C. Siadlak</a>
