site_name: Ludwik C. Siadlak. Lifehacker.
site_url: https://ludwikc.net
docs_dir: ludwikc-pov


exclude: 
  - ludwikc-pov/private/
  - ludwikc-pov/personal/
  - ludwikc-pov/.trash/

theme:
  logo: assets/images/favicon.png
  name: material
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: black
      accent: blue
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.path
    - navigation.top
    - navigation.footer

repo_url: https://github.com/ludwikc/ludwikc.net
repo_name: ludwikc/ludwikc.net

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  analytics:
    provider: google
    property: G-CGKPMN1HP1 
    feedback:
      title: Czy to było ciekawe?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Dzięki!
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ludwikc
  generator: false

plugins:
  - git-committers:
      repository: ludwikc/ludwikc.net
      branch: main
      type: timeago
  - git-revision-date-localized:
      enable_creation_date: true
  - pub-obsidian:
      obsidian_dir: .obsidian
  - pub-meta:
      publish:
        file_default: draft
        file_warn_on_missing: true
        dir_default: published
#      title:
#        key_name: title
      overview:
        default: auto
        key_name: permalink
  - pub-blog:
      teaser_marker: "<!-- more -->"
      searchable_non_posts: false
      posts_per_page: 5
      slug: blog
  - pub-social:
      site_name_in_title:
        location: after
        delimiter: " - "
  

copyright: |
  &copy; 2024 <a href="https://siadlak.com"  target="_blank" rel="noopener">Ludwik C. Siadlak</a>
